#!/usr/bin/env python

import sys
import webalin


def main():
    if sys.argv[-1] == __file__:
        ## No option passed, read from stdin
        markup_or_url = sys.stdin.read()
    else:
        ## Get the info from argv
        markup_or_url = sys.argv[-1]
    data = webalin.analyze(markup_or_url.strip())
    print '\n'.join(data['messages'])


if __name__ == '__main__':
    main()
