#!/usr/bin/env python

import sys
import webalin

## Try to import a JSON library from somewhere, anywhere
try:
    ## Python >= 2.6
    import json
except ImportError:
    try:
        ## Python < 2.6
        import simplejson as json
    except ImportError:
        try:
            ## Django and/or Google App Engine
            from django.utils import simplejson as json
        except ImportError:
            raise ImportError("A suitable JSON library could not be found")

def main():
    if sys.argv[-1] == __file__:
        ## No option passed, read from stdin
        markup_or_url = sys.stdin.read()
    else:
        ## Get the info from argv
        markup_or_url = sys.argv[-1]
    data = webalin.analyze(markup_or_url.strip())
    print '\n'.join(data['messages'])


if __name__ == '__main__':
    main()
